name: Example Workflow

on:
  workflow_dispatch:
    inputs:
      example_input:
        description: 'An example input parameter'
        required: true
        default: 'default_value'
      another_input:
        description: 'Another input parameter'
        required: false
        default: 'optional_value'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print input parameters
        run: |
          echo "Example input: ${{ github.event.inputs.example_input }}"
          echo "Another input: ${{ github.event.inputs.another_input }}"
