name: Example Workflow

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        type: choice
        options:
          - staging
          - production
          - development
        default: staging
      version:
        description: 'Version to deploy'
        required: true
        type: choice
        options:
          - v1.0
          - v1.1
          - v2.0
        default: v1.0

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print input parameters
        run: |
          echo "Environment: ${{ github.event.inputs.environment }}"
          echo "Version: ${{ github.event.inputs.version }}"
          # Add your deployment commands here
