name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker Hub credentials
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Get current version from file
        id: get-version
        run: |
          # Check if version.txt exists and read the version
          if [ -f version.txt ]; then
            current_version=$(cat version.txt)
          else
            current_version="1.0.0"
          fi

          echo "Current version: $current_version"
          echo "current_version=$current_version" >> $GITHUB_ENV

      - name: Determine new image version
        id: version
        run: |
          # Fetch the latest image tags from Docker Hub
          latest_tag=$(curl -s -H "Authorization: token ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" \
                                "https://hub.docker.com/v2/repositories/yourusername/your-image-name/tags/?page_size=100" \
                                | jq -r '.results[].name' | sort -V | tail -n 1)

          # Extract current version parts
          IFS='.' read -r major minor patch <<< "${{ env.current_version }}"

          # Increment the patch version
          new_patch=$((patch + 1))
          new_version="$major.$minor.$new_patch"

          echo "new_version=$new_version" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t yourusername/your-image-name:${{ env.new_version }} .

      - name: Push Docker image
        run: |
          docker push yourusername/your-image-name:${{ env.new_version }}

      - name: Update version file
        run: |
          echo "${{ env.new_version }}" > version.txt
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add version.txt
          git commit -m "Update version to ${{ env.new_version }}"
          git push
